version: '3'
services:
  db:
    build: ./database
    restart: always
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    networks:
      - dev

  nile:
    build: ./cst339
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    networks:
      - dev

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: rmsoft
    ports:
      - "8080:8080"
    networks:
      - dev

networks:
  dev:
    driver: bridge
